name: clinshot
channels:
  - defaults
  - conda-forge
dependencies:
  - scikit-allel=1.3.5
  - pandas=1.4.3
  - python-wget=3.2
  - beautifulsoup4=4.11.1
  - requests=2.28.1
  - cython=0.29.30
  - structlog=21.5.0